import Head from "next/head";
import {
  Flex,
  SimpleGrid,
  Text,
  Box,
  Button,
  useColorMode,
  Switch,
} from "@chakra-ui/react";
import { getHourNow } from "../util/moment";
import { RiMoonLine, RiSunLine } from "react-icons/ri";

export default function Home() {
  const timeInMs = Date.now();
  const { toggleColorMode } = useColorMode();

  return (
    <>
      <Head>
        <title>Skyler - Weather Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex direction="column" h="100vh">
        <Flex width="100%" maxWidth={1480} mx="auto" my="6" px="6">
          <SimpleGrid
            flex="1"
            gap="4"
            templateColumns="1.7fr 1fr"
            minChildWidth="320px"
            align="flex-start"
          >
            <Box>
              <Flex pt="4" justifyContent="space-between">
                <Box>
                  <Text fontSize="4rem" fontWeight="semibold" mt="-20px">
                    {getHourNow(timeInMs)}
                  </Text>
                  <Text>Sexta-feira, 29 de Outubro, 2021</Text>
                  <Text fontSize="1.5rem">
                    <RiSunLine /> Bom dia, Igor
                  </Text>
                </Box>

                <Box>
                  <Flex>
                    <Switch onChange={toggleColorMode} size="lg" />
                  </Flex>
                </Box>
              </Flex>

              <Flex pt="7">
                <SimpleGrid flex="1" gap="4" minChildWidth="50px">
                  <Flex
                    flexDirection="column"
                    align="center"
                    justifyContent="center"
                    borderRadius="1rem"
                    bg="#ddd"
                    p="4"
                  >
                    <RiSunLine />
                    <Text>Sun</Text>
                    <Text>17º</Text>
                  </Flex>
                  <Flex
                    flexDirection="column"
                    align="center"
                    justifyContent="center"
                    borderRadius="1rem"
                    bg="#ddd"
                    p="4"
                  >
                    <RiSunLine />
                    <Text>Sun</Text>
                    <Text>17º</Text>
                  </Flex>
                  <Flex
                    flexDirection="column"
                    align="center"
                    justifyContent="center"
                    borderRadius="1rem"
                    bg="#ddd"
                    p="4"
                  >
                    <RiSunLine />
                    <Text>Sun</Text>
                    <Text>17º</Text>
                  </Flex>
                  <Flex
                    flexDirection="column"
                    align="center"
                    justifyContent="center"
                    borderRadius="1rem"
                    bg="#ddd"
                    p="4"
                  >
                    <RiSunLine />
                    <Text>Sun</Text>
                    <Text>17º</Text>
                  </Flex>
                  <Flex
                    flexDirection="column"
                    align="center"
                    justifyContent="center"
                    borderRadius="1rem"
                    bg="#ddd"
                    p="4"
                  >
                    <RiSunLine />
                    <Text>Sun</Text>
                    <Text>17º</Text>
                  </Flex>
                  <Flex
                    flexDirection="column"
                    align="center"
                    justifyContent="center"
                    borderRadius="1rem"
                    bg="#ddd"
                    p="4"
                  >
                    <RiSunLine />
                    <Text>Sun</Text>
                    <Text>17º</Text>
                  </Flex>
                  <Flex
                    flexDirection="column"
                    align="center"
                    justifyContent="center"
                    borderRadius="1rem"
                    bg="#ddd"
                    p="4"
                  >
                    <RiSunLine />
                    <Text>Sun</Text>
                    <Text>17º</Text>
                  </Flex>
                </SimpleGrid>
              </Flex>
            </Box>
            <Box p={["6", "8"]} pb="4" borderRadius={8}>
              <Text fontSize="large" mb="4">
                Taxa de Abertura
              </Text>
            </Box>
          </SimpleGrid>
        </Flex>
      </Flex>
    </>
  );
}
