import moment from "moment";
import Head from "next/head";
import { getHourNow } from "../util/moment";

export default function Home() {
  const timeInMs = Date.now();
  return (
    <>
      <Head>
        <title>Skyler - Weather Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {getHourNow(timeInMs)}
    </>
  );
}
