import Head from "next/head";
import {
  Flex,
  SimpleGrid,
  Text,
  Box,
  useColorMode,
  Switch,
} from "@chakra-ui/react";
import { getHourNow } from "../util/moment";
import { RiMoonLine, RiSunLine } from "react-icons/ri";

import Image from "next/image";

export default function Home() {
  const timeInMs = Date.now();
  const { colorMode, toggleColorMode } = useColorMode();

  return (
    <>
      <Head>
        <title>Skyler - Weather Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SimpleGrid
        flex="1"
        gap="4"
        templateColumns="1.7fr 1fr"
        minChildWidth="320px"
        align="flex-start"
      >
        <Flex
          direction="column"
          h="100vh"
          bg={colorMode === "light" ? "gray.10" : "gray.900"}
        >
          <Box>
            <Flex
              px="6"
              pt="4"
              my="6"
              mx="auto"
              width="100%"
              maxWidth={920}
              justifyContent="space-between"
            >
              <Box>
                <Text
                  fontSize="4rem"
                  fontWeight="semibold"
                  mt="-20px"
                  color="blue.500"
                >
                  {getHourNow(timeInMs)}
                </Text>
                <Text fontWeight="semibold" fontSize="1.1rem">
                  Sexta-feira, 29 de Outubro, 2021
                </Text>
                <Text fontSize="1.5rem" fontWeight="semibold" color="blue.500">
                  <RiSunLine /> Bom dia, Igor
                </Text>
              </Box>

              <Box>
                <Flex>
                  <Switch onChange={toggleColorMode} size="lg" />
                </Flex>
              </Box>
            </Flex>

            <Flex
              width="100%"
              maxWidth={920}
              mx="auto"
              my="6"
              px="6"
              pt="4"
              justifyContent="space-between"
            >
              <SimpleGrid flex="1" gap="4" minChildWidth="50px">
                <Flex
                  p="4"
                  bg="white"
                  align="center"
                  borderRadius="1rem"
                  flexDirection="column"
                  justifyContent="center"
                >
                  <Image
                    width="150px"
                    height="150px"
                    src="/zaps.png"
                    alt="teste"
                  />
                  <Text fontWeight="semibold" fontSize="1.2rem">
                    Sun
                  </Text>
                  <Text fontWeight="semibold" fontSize="1rem">
                    17º
                  </Text>
                </Flex>
              </SimpleGrid>
            </Flex>
          </Box>
        </Flex>
        <Flex direction="column" h="100vh">
          <Box>
            <Flex
              px="6"
              pt="4"
              my="6"
              mx="auto"
              width="100%"
              maxWidth={600}
              border="1px solid #000"
              justifyContent="space-between"
            >
              teste
            </Flex>
          </Box>

          <Box
            p="6"
            mx="auto"
            width="100%"
            bgGradient="linear(to-r, blue.200, blue.500)"
            align="center"
            maxWidth={600}
            borderRadius="1rem"
            justifyContent="center"
          >
            <Image
              width="250px"
              height="250px"
              src="/cloud-zap.png"
              alt="teste"
            />
            <Text fontSize="1.2rem" fontWeight="semibold" color="white">
              Today, 14 Abril
            </Text>
            <Text fontSize="5rem" fontWeight="semibold" color="white">
              29º
            </Text>
            <Text fontSize="1.2rem" fontWeight="semibold" color="white">
              Sunny
            </Text>
          </Box>

          <Box
            p="6"
            mt="6"
            mx="auto"
            width="100%"
            bgGradient="linear(to-r, pink.200, pink.500)"
            align="center"
            maxWidth={600}
            borderRadius="1rem"
            justifyContent="center"
          >
            <Text fontSize="1.2rem" fontWeight="semibold" color="white">
              Today, 14 Abril
            </Text>
            <Text fontSize="5rem" fontWeight="semibold" color="white">
              29º
            </Text>
            <Text fontSize="1.2rem" fontWeight="semibold" color="white">
              Sunny
            </Text>
          </Box>
        </Flex>
      </SimpleGrid>
    </>
  );
}
